# Generated by Django 4.2.4 on 2023-08-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startyoungukuser",
            name="image",
            field=models.ImageField(
                default="profile_pics/default_dp.jpg", upload_to="profile_pics"
            ),
        ),
    ]
