# Generated by Django 4.1.1 on 2023-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startyoungukuser',
            name='is_buddy',
            field=models.BooleanField(default=False),
        ),
    ]
