# Generated by Django 4.1.5 on 2023-03-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startyoungukuser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
