# Generated by Django 2.1.15 on 2022-09-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startyoungukusers',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
