# Generated by Django 4.1.1 on 2022-09-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startyoungukusers',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='startyoungukusers',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
