# Generated by Django 4.0.7 on 2022-09-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startyoungukuser',
            name='crn_no',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
