# Generated by Django 4.0.7 on 2022-09-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_child_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
