# Generated by Django 4.1.5 on 2023-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_startyoungukuser_is_buddy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddy',
            name='sdp_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buddy',
            name='sdp_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
