# Generated by Django 4.2.4 on 2023-08-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_startyoungukuser_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="startyoungukuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
