# Generated by Django 4.0.7 on 2022-09-28 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_startyoungukuser_image_alter_startyoungukuser_crn_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('date', models.DateTimeField(auto_created=True)),
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Female'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('class_std', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=50)),
                ('hobbies', models.CharField(default='0000000000', max_length=10)),
                ('mentor', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('date', models.DateTimeField(auto_created=True)),
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('hobbies', models.CharField(default='0000000000', max_length=10)),
                ('occupation', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
