# Generated by Django 4.1.1 on 2022-09-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_startyoungukusers_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startyoungukusers',
            options={'ordering': ('email', 'display_name')},
        ),
        migrations.RenameField(
            model_name='startyoungukusers',
            old_name='email_id',
            new_name='email',
        ),
    ]
