# Generated by Django 4.1.5 on 2023-03-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_startyoungukuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startyoungukuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
