# Generated by Django 4.1.1 on 2022-09-25 05:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_startyoungukusers_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartYoungUKUsers',
            new_name='StartYoungUKUser',
        ),
        migrations.AlterModelOptions(
            name='startyoungukuser',
            options={},
        ),
    ]
