# Generated by Django 4.1.5 on 2023-04-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_buddy_sdp_active_buddy_sdp_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buddy',
            options={'verbose_name_plural': 'Buddies'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='startyoungukuser',
            options={'verbose_name_plural': 'StartYoung UK Users'},
        ),
    ]
