# Generated by Django 4.1.1 on 2022-09-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_startyoungukusers_startyoungukuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startyoungukuser',
            name='user_type',
            field=models.CharField(choices=[('I', 'Individual'), ('C', 'Corporate')], max_length=10),
        ),
    ]
