# Generated by Django 4.1.5 on 2023-04-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_buddy_options_alter_child_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddy",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                    ("opted out", "opted out"),
                ],
                default="pending",
                max_length=256,
            ),
        ),
    ]
