# Generated by Django 4.2.4 on 2023-08-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_startyoungukuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startyoungukuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
