# Generated by Django 4.1.1 on 2022-09-25 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_startyoungukuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startyoungukuser',
            name='crn_no',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.DecimalValidator(decimal_places=8, max_digits=8)]),
            preserve_default=False,
        ),
    ]
