# Generated by Django 4.2.4 on 2023-08-13 16:30

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_startyoungukuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startyoungukuser",
            name="crn_no",
            field=models.CharField(
                default="00000000",
                max_length=8,
                validators=[django.core.validators.MinLengthValidator(limit_value=8)],
                verbose_name="CRN Number",
            ),
        ),
        migrations.AlterField(
            model_name="startyoungukuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="startyoungukuser",
            name="sdp_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="RDP Amount"),
        ),
        migrations.AlterField(
            model_name="startyoungukuser",
            name="sdp_frequency",
            field=models.CharField(
                choices=[
                    ("W", "Weekly"),
                    ("F", "Fortnightly"),
                    ("M", "Monthly"),
                    ("N", "None"),
                ],
                default="N",
                max_length=10,
                verbose_name="RDP Frequency",
            ),
        ),
    ]
