# Generated by Django 4.1.5 on 2023-03-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_startyoungukuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startyoungukuser',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
