# Generated by Django 4.1.5 on 2023-03-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_startyoungukuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startyoungukuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
