# Generated by Django 4.0.7 on 2022-09-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220925_1154'),
        ('users', '0006_alter_startyoungukuser_crn_no'),
    ]

    operations = [
    ]
