# Generated by Django 4.1.5 on 2023-04-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_startyoungukuser_sdp_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddy',
            name='sdp_active',
        ),
    ]
