# Generated by Django 4.0.7 on 2023-03-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_startyoungukuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='approver',
            field=models.EmailField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=256),
        ),
        migrations.AddField(
            model_name='startyoungukuser',
            name='is_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
