# Generated by Django 4.0.7 on 2023-03-24 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_mentor_approver_mentor_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buddy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hobbies', models.CharField(default='0000000000', max_length=10)),
                ('date_status_modified', models.DateTimeField(auto_now_add=True)),
                ('occupation', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=256)),
                ('approver', models.EmailField(max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
