# Generated by Django 4.1.6 on 2023-03-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_mentor_is_approved_mentor_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="startyoungukuser",
            name="is_coordinator",
            field=models.BooleanField(default=False),
        ),
    ]
