# Generated by Django 4.2.4 on 2023-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_remove_startyoungukuser_display_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="startyoungukuser",
            options={"verbose_name_plural": "Start Young UK Users"},
        ),
    ]
