# Generated by Django 4.0.7 on 2022-09-25 10:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('trxn_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=50)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('amount', models.PositiveIntegerField()),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
