# Generated by Django 2.1.15 on 2022-09-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('trxn_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
