# Generated by Django 2.1.15 on 2022-09-25 05:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donations',
            name='email_id',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donations',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='donations',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donations',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
