# Generated by Django 4.0.7 on 2022-09-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='campaign_id',
            field=models.IntegerField(default=0),
        ),
    ]
