# Generated by Django 4.0.7 on 2022-09-29 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_donation_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
