# Generated by Django 4.1.5 on 2023-03-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_donation_is_anonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='mobile_no',
            new_name='mobile_number',
        ),
    ]
