# Generated by Django 4.1.5 on 2023-04-28 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_donation_is_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_donation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
