# Generated by Django 4.0.7 on 2022-09-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_title', models.CharField(max_length=50)),
                ('campaign_description', models.TextField(max_length=200)),
                ('collection_target', models.IntegerField()),
                ('campaign_image', models.ImageField(default='default.jpg', upload_to='campaign_pics')),
            ],
        ),
    ]
