# Generated by Django 4.0.7 on 2022-09-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("campaign_id", models.AutoField(primary_key=True, serialize=False)),
                ("campaign_title", models.CharField(max_length=50)),
                ("campaign_description", models.TextField(max_length=200)),
                ("collection_target", models.IntegerField()),
                ("campaign_deadline", models.DateField()),
                (
                    "campaign_image",
                    models.ImageField(default="default.jpg", upload_to="campaign_pics"),
                ),
                ("is_active", models.BooleanField(null=False, default=True)),
                ("slug", models.SlugField(null=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=400)),
                ("end_date", models.DateField(null=False)),
                ("job_paid",  models.BooleanField(null=False, default=False)),
                ("duration", models.TextField(default="5 months", max_length=50)),
                ("form_url", models.URLField(max_length=100)),
                ("position_filled", models.BooleanField(null=False)),
            ],
        ),
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                ("affiliation_id", models.AutoField(primary_key=True, serialize=False)),
                ("affiliation_name", models.CharField(max_length=50)),
                ("affiliation_description", models.TextField(max_length=200)),
                (
                    "affiliation_image",
                    models.ImageField(
                        default="default.jpg", upload_to="affiliation_pics"
                    ),
                ),
                ("affiliation_join_date", models.DateField()),
                ("affiliation_display", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="EmailContent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("approved", "Final Step: Setting up recurring donation plan"),
                            ("rejected", "Buddy Rejection Email"),
                            ("Letter", "Buddy Letter Reminder"),
                            ("final", "Welcome to SYUK"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("header", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("attachment", models.FileField(blank=True, upload_to="attachments/")),
                ("attachment2", models.FileField(blank=True, upload_to="attachments/")),
                ("attachment3", models.FileField(blank=True, upload_to="attachments/")),
                ("attachment4", models.FileField(blank=True, upload_to="attachments/")),
                ("attachment5", models.FileField(blank=True, upload_to="attachments/")),
                ("signature", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="opportunity",
            options={"verbose_name_plural": "Opportunities"},
        ),


    ]
