# Generated by Django 4.0.7 on 2022-09-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("campaign_id", models.AutoField(primary_key=True, serialize=False)),
                ("campaign_title", models.CharField(max_length=50)),
                ("campaign_description", models.TextField(max_length=200)),
                ("collection_target", models.IntegerField()),
                ("campaign_deadline", models.DateField()),
                (
                    "campaign_image",
                    models.ImageField(default="default.jpg", upload_to="campaign_pics"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=400)),
                ("end_date", models.DateField(null=False)),
                ("job_paid",  models.BooleanField(null=False, default=False)),
                ("duration", models.TextField(default="5 months", max_length=50)),
                ("form_url", models.URLField(max_length=100)),
                ("position_filled", models.BooleanField(null=False)),
            ],
        ),
    ]
