# Generated by Django 4.2.4 on 2023-08-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_campaign_campaign_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="affiliation_image",
            field=models.ImageField(
                default="affiliation_pics/default_affiliation.jpg",
                upload_to="affiliation_pics",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_image",
            field=models.ImageField(
                default="campaign_pics/default_campaign.jpg", upload_to="campaign_pics"
            ),
        ),
    ]
