# Generated by Django 4.0.7 on 2022-09-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_campaigns_campaign_deadline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaigns',
            new_name='Campaign',
        ),
    ]
