# Generated by Django 4.1.6 on 2023-02-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_coporate_sponsors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coporate_sponsors",
        ),
    ]
