# Generated by Django 4.1.6 on 2023-02-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_coporate_sponsors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                ("affiliation_id", models.AutoField(primary_key=True, serialize=False)),
                ("affiliation_name", models.CharField(max_length=50)),
                ("affiliation_description", models.TextField(max_length=200)),
                (
                    "affiliation_image",
                    models.ImageField(
                        default="default.jpg", upload_to="affiliation_pics"
                    ),
                ),
                ("affiliation_join_date", models.DateField()),
                ("affiliation_display", models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name="Coporate_sponsors",
        ),
    ]
