# Generated by Django 4.1.5 on 2023-02-24 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_campaign_campaign_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="duration",
            field=models.TextField(default="5 months", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opportunity",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opportunity",
            name="position_filled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="salary",
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
