# Generated by Django 4.1.6 on 2023-02-25 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_delete_coporate_sponsors"),
        ("home", "0003_alter_campaign_campaign_image"),
    ]

    operations = []
