# Generated by Django 4.1.6 on 2023-02-25 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_affiliation_delete_coporate_sponsors"),
        ("home", "0005_opportunity_duration_opportunity_end_date_and_more"),
    ]

    operations = []
