# Generated by Django 4.0.7 on 2023-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_emailcontent_alter_opportunity_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcontent",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("approved", "Final Step: Setting up SDP"),
                    ("rejected", "Buddy Rejection Email"),
                    ("Letter", "Buddy Letter Reminder"),
                    ("final", "Welcome to SYUK"),
                ],
                max_length=50,
            ),
        ),
    ]
