# Generated by Django 4.0.7 on 2023-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_emailcontent_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='email_type',
            field=models.CharField(choices=[('approved', 'Buddy Approval Email'), ('rejected', 'Buddy Rejection Email'), ('Letter', 'Buddy Letter Reminder')], max_length=50),
        ),
    ]
