# Generated by Django 4.2.4 on 2023-08-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_merge_20230225_1629"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="affiliation_image",
            field=models.ImageField(
                default="affiliation_pics/default_affiliation.jpg",
                upload_to="affiliation_pics",
            ),
        ),
    ]
