# Generated by Django 4.1.6 on 2023-02-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("member_name", models.CharField(max_length=100)),
                ("member_title", models.CharField(max_length=50)),
                ("member_description", models.TextField(max_length=200)),
                (
                    "member_image",
                    models.ImageField(
                        default="default_member.jpg", upload_to="team_member_pics"
                    ),
                ),
            ],
        ),
    ]
