# Generated by Django 4.2.4 on 2023-08-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="member_image",
            field=models.ImageField(
                default="team_member_pics/default_member.jpg",
                upload_to="team_member_pics",
            ),
        ),
    ]
