# Generated by Django 4.1.6 on 2023-02-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_title", models.CharField(max_length=100)),
                (
                    "image_image",
                    models.ImageField(
                        default="default_image.jpg", upload_to="gallery_pics"
                    ),
                ),
            ],
        ),
    ]
