# Generated by Django 4.1 on 2023-08-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_teammember_member_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="charitydetail",
            name="number_children_helped",
            field=models.IntegerField(null=True),
        ),
    ]
