# Generated by Django 4.1.1 on 2023-02-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_galleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image_image',
            new_name='gallery_image',
        ),
    ]
