# Generated by Django 4.1 on 2023-08-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_charitydetail_number_children_helped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charitydetail",
            name="number_children_helped",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
