# Generated by Django 4.0.7 on 2023-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_image_image_galleryimage_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='gallery_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=5),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery_image',
            field=models.FileField(default='default_image.jpg', upload_to='gallery_pics'),
        ),
    ]
