# Generated by Django 4.1 on 2023-10-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_alter_charitydetail_number_children_helped"),
    ]

    operations = [
        migrations.AddField(
            model_name="charitydetail",
            name="buddies_onboarded",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charitydetail",
            name="campaigns_so_far",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charitydetail",
            name="number_of_sponsors",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
