# Generated by Django 4.0.7 on 2023-03-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_galleryimage_gallery_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery_type',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery_image',
            field=models.ImageField(default='default_image.jpg', upload_to='gallery_pics'),
        ),
    ]
