# Generated by Django 4.1 on 2023-10-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0005_charitydetail_buddies_onboarded_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="charitydetail",
            old_name="number_of_sponsors",
            new_name="number_of_schools",
        ),
    ]
